version: 2
updates:
  # Bundler (Ruby)
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"

  # npm (JavaScript)
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
