inherit_gem:
  rubocop-discourse: stree-compat.yml
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent
Layout/LineLength:
  Enabled: true
Security/CompoundHash:
  Enabled: true
