plugins:
  post_folding_enabled:
    default: true
    client: true
  post_folding_manipulatable_groups:
    client: true
    type: group_list
    list_type: compact
    default: "1|2|3|14" # by order: @admin, @moderators, @staff, @trust_level_4
    allow_any: false
  post_folding_banned_groups:
    client: true
    type: group_list
    list_type: compact
    default: "10" # @trust_level_0
    allow_any: false
  post_folding_banned_users:
    client: true
    type: list
    list_type: compact
    default: ""
    choices: "User.where('username IS NOT NULL').map { |x| x.username }"
    allow_any: false
  all_topics_post_folding_capable:
    default: false
    client: true
  post_folding_capable_categories:
    client: true
    type: category_list
    list_type: compact
    default: ""
    allow_any: false
  post_folding_capable_tags:
    client: true
    type: tag_list
    list_type: compact
    default: ""
    allow_any: false
  post_folding_disable_confirm:
    default: false
    client: true
  fold_post_cooldown:
    client: true
    type: integer
    default: 10
  unfold_post_cooldown:
    client: true
    type: integer
    default: 10
  topic_enable_post_folding_dooldown:
    client: true
    type: integer
    default: 10
  topic_disable_post_folding_cooldown:
    client: true
    type: integer
    default: 10
