plugins:
  post_folding_enabled:
    default: true
    client: true
  post_folding_manipulatable_groups:
    client: true
    type: group_list
    list_type: compact
    default: "1|2|3|14" # by order: @admin, @moderators, @staff, @trust_level_4
    allow_any: false
    refresh: true
